-- Run this once in Supabase Dashboard > SQL Editor.
-- Community posts and comments are tied to the logged-in auth user.

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null check (char_length(title) between 1 and 120),
  content text not null default '',
  author_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  author_name text not null default '덕친소 회원',
  author_avatar_url text,
  views integer not null default 0 check (views >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.community_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 1000),
  author_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  author_name text not null default '덕친소 회원',
  author_avatar_url text,
  created_at timestamptz not null default now()
);

create index if not exists community_posts_created_at_idx
  on public.community_posts (created_at desc);
create index if not exists community_posts_author_id_idx
  on public.community_posts (author_id, created_at desc);
create index if not exists community_comments_post_id_idx
  on public.community_comments (post_id, created_at asc);
create index if not exists community_comments_author_id_idx
  on public.community_comments (author_id, created_at desc);

-- Store the nickname/avatar from profiles at the moment the post or comment is written.
-- auth.uid() is set server-side, so a client cannot submit another user's identity.
create or replace function public.set_community_author_snapshot()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_name text;
  profile_avatar text;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  new.author_id := auth.uid();
  select display_name, avatar_url
    into profile_name, profile_avatar
    from public.profiles
   where id = auth.uid();

  new.author_name := coalesce(profile_name, '덕친소 회원');
  new.author_avatar_url := profile_avatar;
  return new;
end;
$$;

drop trigger if exists community_posts_author_snapshot on public.community_posts;
create trigger community_posts_author_snapshot
before insert on public.community_posts
for each row execute function public.set_community_author_snapshot();

drop trigger if exists community_comments_author_snapshot on public.community_comments;
create trigger community_comments_author_snapshot
before insert on public.community_comments
for each row execute function public.set_community_author_snapshot();

alter table public.community_posts enable row level security;
alter table public.community_comments enable row level security;

drop policy if exists "community_posts_are_readable" on public.community_posts;
create policy "community_posts_are_readable" on public.community_posts
  for select to anon, authenticated using (true);

drop policy if exists "users_create_own_community_posts" on public.community_posts;
create policy "users_create_own_community_posts" on public.community_posts
  for insert to authenticated with check (author_id = auth.uid());

drop policy if exists "users_update_own_community_posts" on public.community_posts;
create policy "users_update_own_community_posts" on public.community_posts
  for update to authenticated using (author_id = auth.uid()) with check (author_id = auth.uid());

drop policy if exists "users_delete_own_community_posts" on public.community_posts;
create policy "users_delete_own_community_posts" on public.community_posts
  for delete to authenticated using (author_id = auth.uid());

drop policy if exists "community_comments_are_readable" on public.community_comments;
create policy "community_comments_are_readable" on public.community_comments
  for select to anon, authenticated using (true);

drop policy if exists "users_create_own_community_comments" on public.community_comments;
create policy "users_create_own_community_comments" on public.community_comments
  for insert to authenticated with check (author_id = auth.uid());

drop policy if exists "users_update_own_community_comments" on public.community_comments;
create policy "users_update_own_community_comments" on public.community_comments
  for update to authenticated using (author_id = auth.uid()) with check (author_id = auth.uid());

drop policy if exists "users_delete_own_community_comments" on public.community_comments;
create policy "users_delete_own_community_comments" on public.community_comments
  for delete to authenticated using (author_id = auth.uid());

-- Keep direct UPDATE blocked to clients. This small RPC only increments a view count.
create or replace function public.increment_community_post_view(target_post_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.community_posts
     set views = views + 1
   where id = target_post_id;
end;
$$;

grant execute on function public.increment_community_post_view(bigint) to anon, authenticated;

notify pgrst, 'reload schema';
